Removed goof up from last commit and extraneous junk in the runner.

diff --git a/src/universal/bin/sbt b/src/universal/bin/sbt
--- a/src/universal/bin/sbt
+++ b/src/universal/bin/sbt
@@ -128,58 +128,17 @@ dlog () {
   [[ $debug ]] && echoerr "$@"
 }
 
-sbtjar_07_url () {
-  echo "http://simple-build-tool.googlecode.com/files/sbt-launch-${1}.jar"
-}
-sbtjar_release_url () {
-  echo "http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-tools.sbt/sbt-launch/$sbt_version/sbt-launch.jar"
-}
-sbtjar_new_release_url () {
-  echo "http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/$sbt_version/sbt-launch.jar"
-}
-jar_url () {
-  case $sbt_version in
-      0.7.4*) sbtjar_07_url 0.7.4 ;;
-      0.7.5*) sbtjar_07_url 0.7.5 ;;
-      0.7.7*) sbtjar_07_url 0.7.7 ;;
-       0.7.*) sbtjar_07_url 0.7.7 ;;
-       0.9.*) sbtjar_release_url ;;
-      0.10.*) sbtjar_release_url ;;
-      0.11.1) sbtjar_release_url ;;
-      0.11.2) sbtjar_release_url ;;
-      0.11.*) sbtjar_new_release_url ;;
-           *) sbtjar_new_release_url ;;
-  esac
-}
-
 jar_file () {
-  if [[ -f "/usr/lib/sbt/$1/sbt-launch.jar" ]]; then
-    echo "/usr/lib/sbt/$1/sbt-launch.jar"
+  if [[ -f "$(dirname $0)/sbt-launch.jar" ]]; then
+    echo "$(dirname $0)/sbt-launch.jar"
   else
-    echo "$script_dir/.lib/$1/sbt-launch.jar"
+    echo "Could not find sbt-launch.jar in $(dirname $0)"
+    exit 1
   fi
-}
-
-download_url () {
-  local url="$1"
-  local jar="$2"
-
-  echo "Cannot find sbt launcher $sbt_version"
-  echo "Please download: "
-  echo "  From  $url"
-  echo "    To  $jar"
-
-  exit 1
 }
 
 acquire_sbt_jar () {
-  if [[ ! $sbt_version ]]; then
-    sbt_version=$sbt_release_version
-  fi
-
-  sbt_jar="$(jar_file $sbt_version)"
-
-  [[ -f "$sbt_jar" ]] || download_url "$(jar_url)" "$sbt_jar"
+  sbt_jar="$(jar_file)"
 }
 
 usage () {
